 CREATE TABLE IF NOT EXISTS STATUS_ENUM(
   ENUM_ID INT(1),
   DESCRIPTION VARCHAR2(50)   
   );
   
    
   CREATE TABLE IF NOT EXISTS DEGREE_ENUM(
   ENUM_ID INT(1),
   DESCRIPTION VARCHAR2(50)
   );
   
   
CREATE TABLE IF NOT EXISTS CANDIDATE(
	PERSON_ID INT(16) AUTO_INCREMENT,
   FIRST_NAME VARCHAR2(100),
   LAST_NAME VARCHAR2(100),
   PHONE_NUMBER VARCHAR2(12),
   EMAIL_ADDRESS VARCHAR2(64),  
   
   START_DATE DATE,
   DEGREE_EN INT(1),
   MAJOR VARCHAR2(20),
   SKILL_SET VARCHAR2(100),
   GRADUATION_DATE DATE,
   STATUS_EN INT(1),
   COMMENTS VARCHAR2(100),
   RESUME BLOB,
   
     
   PRIMARY KEY (PERSON_ID),
   FOREIGN KEY (DEGREE_EN) REFERENCES DEGREE_ENUM(ENUM_ID),
   FOREIGN KEY (STATUS_EN) REFERENCES STATUS_ENUM(ENUM_ID)
 
   );   

   
--INSERT INTO STATUS_ENUM (ENUM_ID, DESCRIPTION) VALUES (1,'F1');
--INSERT INTO STATUS_ENUM  (ENUM_ID, DESCRIPTION) VALUES (2,'H1B');
--INSERT INTO STATUS_ENUM  (ENUM_ID, DESCRIPTION) VALUES (3,'F1-OPT');
--INSERT INTO STATUS_ENUM  (ENUM_ID, DESCRIPTION) VALUES (4,'GREEN CARD');
--INSERT INTO STATUS_ENUM   (ENUM_ID, DESCRIPTION) VALUES (5,'U.S CITIZEN');
--INSERT INTO DEGREE_ENUM  (ENUM_ID, DESCRIPTION) VALUES (1,'BACHELORS');
--INSERT INTO DEGREE_ENUM   (ENUM_ID, DESCRIPTION) VALUES (2,'MASTERS');
--INSERT INTO DEGREE_ENUM (ENUM_ID, DESCRIPTION) VALUES (3,'EXPERIENCED');
--
--INSERT INTO CANDIDATE (PERSON_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL_ADDRESS, START_DATE, DEGREE_EN, MAJOR, SKILL_SET, GRADUATION_DATE, STATUS_EN, COMMENTS, RESUME)
--VALUES (1,'BRAD','MARK','123-456-7890','brad.mark@gmail.com','2016-07-01',2,'CS','C,C++,JAVA','2016-05-01',1,'PASSED ALL TESTS', RAWTOHEX('HELLO'));

   
   
--UPDATE DEGREE_ENUM SET DESCRIPTION='ASSOCIATE DEGREE' WHERE ENUM_ID=3
--INSERT INTO DEGREE_ENUM   (ENUM_ID, DESCRIPTION) VALUES (5,'MASTER DEGREE')
--INSERT INTO DEGREE_ENUM   (ENUM_ID, DESCRIPTION) VALUES (4,'BACHELOR DEGREE')
--INSERT INTO DEGREE_ENUM   (ENUM_ID, DESCRIPTION) VALUES (6,'DOCTORATE')
--UPDATE DEGREE_ENUM SET DESCRIPTION='CERTIFICATE' WHERE ENUM_ID=2
--UPDATE DEGREE_ENUM SET DESCRIPTION='HIGHSCHOOL DIPLOMA / GED ' WHERE ENUM_ID=1
--
--DELETE FROM STATUS_ENUM WHERE ENUM_ID=5
--UPDATE STATUS_ENUM SET DESCRIPTION='HIRED' WHERE ENUM_ID=4
--UPDATE STATUS_ENUM SET DESCRIPTION='DISCONTINUED PURSUIT' WHERE ENUM_ID=3
--UPDATE STATUS_ENUM SET DESCRIPTION='WAITING ON RESPONSE' WHERE ENUM_ID=2
--UPDATE STATUS_ENUM SET DESCRIPTION='INTERVIEWING' WHERE ENUM_ID=1
  