   CREATE TABLE IF NOT EXISTS EMPLOYEETYPE_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
   
   );
   
   CREATE TABLE IF NOT EXISTS EMPLOYEEDEPT_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
      );

     CREATE TABLE IF NOT EXISTS USERROLE_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
      );

CREATE TABLE IF NOT EXISTS EMPLOYEE (
   EMPLOYEE_ID INT(32) AUTO_INCREMENT,
   FIRST_NAME VARCHAR(100),
   LAST_NAME VARCHAR(100),
   PHONE_NUMBER VARCHAR(10),
   EMAIL_ADDRESS VARCHAR(20), 
   
   START_DATE DATE,
   END_DATE DATE,
   EMPLOYEETYPE_EN INT(1),
   EMPLOYEEDEPTTYPE_EN INT(1),
   USERROLE_EN INT(1),
   PASSWORD VARCHAR(10),
   
   PRIMARY KEY (EMPLOYEE_ID),
   FOREIGN KEY (EMPLOYEETYPE_EN) REFERENCES EMPLOYEETYPE_ENUM(ENUM_ID),
   FOREIGN KEY (EMPLOYEEDEPTTYPE_EN) REFERENCES EMPLOYEEDEPT_ENUM(ENUM_ID),
   FOREIGN KEY (USERROLE_EN) REFERENCES USERROME_ENUM(ENUM_ID)
     
   );
