CREATE TABLE IF NOT EXISTS TRAININGSTATUS_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
   
   );
   
   CREATE TABLE IF NOT EXISTS BOOTCAMPTYPE_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
      );

     CREATE TABLE IF NOT EXISTS DURATIONUNIT_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
      );

CREATE TABLE IF NOT EXISTS TRAININGMASTER (
   TRAINING_ID INT(32) AUTO_INCREMENT,
   TITLE VARCHAR(100),
   DESCRIPTION VARCHAR(100),
   DURATION INT(3),
   DURATIONUNIT_EN INT(1),
   URL VARCHAR(100),
   TRAININGSTATUS_EN INT(1),
   BOOTCAMPTYPE_EN INT(1),

   PRIMARY KEY (TRAINING_ID),
   FOREIGN KEY (DURATIONUNIT_EN) REFERENCES DURATIONUNIT_ENUM(ENUM_ID),
   FOREIGN KEY (TRAININGSTATUS_EN) REFERENCES TRAININGSTATUS_ENUM(ENUM_ID),
   FOREIGN KEY (DURATIONUNIT_EN) REFERENCES DURATIONUNIT_ENUM(ENUM_ID)
     
   ); 