CREATE TABLE IF NOT EXISTS TRAININGSTATUS_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
   
   );
   
   CREATE TABLE IF NOT EXISTS BOOTCAMPTYPE_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
      );

     CREATE TABLE IF NOT EXISTS DURATIONUNIT_ENUM(
    ENUM_ID INT(1),
   DESCRIPTION VARCHAR(50)  
      );

CREATE TABLE IF NOT EXISTS TRAININGMASTER (
   TRAINING_ID INT(32) AUTO_INCREMENT,
   TITLE VARCHAR(100),
   DESCRIPTION VARCHAR(100),
   DURATION INT(3),
   DURATIONUNIT_EN INT(1),
   URL VARCHAR(100),
   TRAININGSTATUS_EN INT(1),
   BOOTCAMPTYPE_EN INT(1),

   PRIMARY KEY (TRAINING_ID),
   FOREIGN KEY (DURATIONUNIT_EN) REFERENCES DURATIONUNIT_ENUM(ENUM_ID),
   FOREIGN KEY (TRAININGSTATUS_EN) REFERENCES TRAININGSTATUS_ENUM(ENUM_ID),
   FOREIGN KEY (DURATIONUNIT_EN) REFERENCES DURATIONUNIT_ENUM(ENUM_ID)
     
   ); 
   
CREATE TABLE IF NOT EXISTS COURSE(
   COURSE_ID INT(5),
   COURSE_TITLE VARCHAR(50), 
   COURSE_DESCRIPTION VARCHAR(100),
   COURSE_URL VARCHAR(50),
   
   PRIMARY KEY (COURSE_ID)
   
   );
   
-- INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, COURSE_DESCRIPTION, COURSE_URL) VALUES (1,'HTML', 'Learn HTML!', 'www.htmlcourse.com');
-- INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, COURSE_DESCRIPTION, COURSE_URL) VALUES (2,'Java', 'Learn Java!', 'www.Javacourse.com');
-- INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, COURSE_DESCRIPTION, COURSE_URL) VALUES (3,'Thymeleaf', 'Learn Thymeleaf!', 'www.Thymeleafcourse.com');
   
   
--  INSERT INTO DURATIONUNIT_ENUM (ENUM_ID, DESCRIPTION) VALUES (1,'Hours');
--  INSERT INTO DURATIONUNIT_ENUM (ENUM_ID, DESCRIPTION) VALUES (2,'Days');
--  INSERT INTO DURATIONUNIT_ENUM (ENUM_ID, DESCRIPTION) VALUES (3,'Weeks');
--    
--  INSERT INTO TRAININGSTATUS_ENUM (ENUM_ID, DESCRIPTION) VALUES (1,'Active'); 
--  INSERT INTO TRAININGSTATUS_ENUM (ENUM_ID, DESCRIPTION) VALUES (2,'Inactive'); 
--  INSERT INTO TRAININGSTATUS_ENUM (ENUM_ID, DESCRIPTION) VALUES (3,'On-hold'); 
--    
--  INSERT INTO BOOTCAMPTYPE_ENUM (ENUM_ID, DESCRIPTION) VALUES (1,'Development'); 
--  INSERT INTO BOOTCAMPTYPE_ENUM (ENUM_ID, DESCRIPTION) VALUES (2,'Testing'); 
--  INSERT INTO BOOTCAMPTYPE_ENUM (ENUM_ID, DESCRIPTION) VALUES (3,'Automation'); 
--  INSERT INTO BOOTCAMPTYPE_ENUM (ENUM_ID, DESCRIPTION) VALUES (4,'Management');
